In [ ]:
import numpy as np

**Create a NumPy array 'arr' of integers from 0 to 5 and print its data type**

In [ ]:
arr=np.arange(0,5)

In [ ]:
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr.dtype

dtype('int64')

**Given a NumPy array 'arr', check if its data type is float64.**


In [ ]:
arr=np.array([1.5,2.6,3.7])

In [ ]:
arr.dtype

dtype('float64')

**Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.**

In [ ]:
arr=np.array([1,2,3],dtype=np.complex128)

In [ ]:
arr

array([1.+0.j, 2.+0.j, 3.+0.j])

**Convert an existing NumPy array 'arr' of integers to float32 data type.**

In [ ]:
arr1=arr.astype(np.float32)

<ipython-input-10-24bf9ab11c70>:1: ComplexWarning: Casting complex values to real discards the imaginary part
  arr1=arr.astype(np.float32)


In [ ]:
arr1

array([1., 2., 3.], dtype=float32)

**Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.**

In [ ]:
arr=np.arange(1,10,dtype=np.float64)

In [ ]:
arr.astype(np.float32)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

**Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.**

In [ ]:
def array_attributes(arr):
  return arr.shape,arr.size,arr.dtype

In [ ]:
array_attributes(np.array([1,2,3,4,5]))

((5,), 5, dtype('int64'))

**Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.**

In [ ]:
def array_dimension(arr):
  return arr.ndim

In [ ]:
array_dimension(np.array([1,2,3,4,5]))

1

** Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes**

In [ ]:
def function_item_size_info(arr):
  return arr.itemsize,arr.size*arr.itemsize

In [ ]:
function_item_size_info(np.array([1,2,3,4,5]))

(8, 40)

**Create a function array_strides that takes a NumPy array as input and returns the strides of the array.**

In [ ]:
def array_strides(arr):
 return  arr.strides

In [ ]:
array_strides(np.array([1,2,3,4,5]))

(8,)

**Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array**

In [ ]:
def shape_stride_relationship(arr):
  return arr.shape,arr.strides

In [ ]:
shape_stride_relationship(np.ones((1,2)))

((1, 2), (16, 8))

** Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.**

In [ ]:
def create_zeros_array(n):
  return np.zeros(n)

In [ ]:
create_zeros_array(5)

array([0., 0., 0., 0., 0.])

**Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`**

In [ ]:
def create_ones_matrix(rows,column):
  arr=np.ones((rows,column))
  mat=np.matrix(arr)
  return mat

In [ ]:
create_ones_matrix(2,3)

matrix([[1., 1., 1.],
        [1., 1., 1.]])

 **Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.**

In [ ]:
def genrate_range_array(start,stop,step):
  return np.arange(start,stop,step)

In [ ]:
genrate_range_array(1,5,1)

array([1, 2, 3, 4])

**Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive)**

In [ ]:
def genrate_linear_space(start,stop,nos):
  return np.linspace(start,stop,nos)

In [ ]:
genrate_linear_space(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

**Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.**

In [ ]:
def create_identity_matrix(n):
  return np.eye(n)

In [ ]:
create_identity_matrix(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Write a function that takes a Python list and converts it into a NumPy array.**

In [ ]:
def listtoarray(lis):
  return np.array(lis)

In [ ]:
listtoarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

**Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.**


In [ ]:
arr=np.arange(1,10,2)

In [ ]:
arr1=arr.view()

In [ ]:
arr1

array([1, 3, 5, 7, 9])

**Write a function that takes two NumPy arrays and concatenates them along a specified axis**

In [ ]:
def concat(arr1,arr2):
  return np.concatenate((arr1,arr2),axis=0)

In [ ]:
arr1=np.arange(1,10)
arr2=np.arange(1,5)

In [ ]:
concat(arr1,arr2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4])

**Write a function that takes two NumPy arrays and concatenates them along a specified axis**

In [ ]:
arr=np.arange(1,5).reshape(2,2)

In [ ]:
arr1=np.arange(1,9).reshape(4,2)

In [ ]:
np.concatenate((arr,arr1),axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**Write a function that vertically stacks multiple NumPy arrays given as a list**

In [ ]:
def verstack(lis1,lis2):
  arr1=np.array(lis1)
  arr2=np.array(lis2)
  return np.vstack((arr1,arr2))

In [ ]:
verstack(np.zeros((2,3)),np.ones((1,3)))

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.]])

**Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.**

In [ ]:
def array(start,stop,step):
  return np.arange(start,stop+1,step)

In [ ]:
array(1,6,1)

array([1, 2, 3, 4, 5, 6])

**Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).**

In [ ]:
def genrate_linear_space(start,stop,nos):
  return np.linspace(start,stop,nos)

In [ ]:
genrate_linear_space(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive)**

In [ ]:
def logspace(start,stop,nos):
  return np.logspace(start,stop,nos)

In [ ]:
logspace(1,10,5)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [ ]:
import pandas as pd

 **Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.**

In [ ]:
arr=np.random.randint(1,100,(5,3))

In [ ]:
df=pd.DataFrame(arr)

In [ ]:
df

0   1   2
0  83  50  55
1  69  23  68
2  19  87  61
3  31  49  85
4  51  47  10

**Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.**

In [304]:
def func(df,col):
  df[col]=np.where(df[col]<0,0,df[col])
  return df



In [305]:
df=pd.DataFrame([[-1,2,3],[4,5,-5]])
func(df,col=0)

0  1  2
0  0  2  3
1  4  5 -5

**Access the 3rd element from the given NumPy array**


In [ ]:
arr=np.array([10,20,30,40,50])

In [ ]:
arr[2]

30

In [ ]:
arr[3]

40

 **Retrieve the element at index (1, 2) from the 2D NumPy array**

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
arr_2d[1,2]

6

**Using boolean indexing, extract elements greater than 5 from the given NumPy array**

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7])

In [ ]:
arr[arr>5]

array([ 8, 10,  7])

**Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[2:5+1]

array([3, 4, 5, 6])

**Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.**

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
arr_2d[0:2,1:]

array([[2, 3],
       [5, 6]])

**Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.**

In [283]:
def extract(arr,index):
  row=index[:,0]
  col=index[:,1]
  return arr[row,col]


In [284]:

arr=np.array([[1,2,3],[4,5,6],[5,6,4]])
index=np.array([[0,0],[1,2],[2,2]])

extract(arr,index)

array([1, 6, 4])

**create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.**

In [ ]:
def func(arr,threshold):
  arr=arr[arr>threshold]
  return arr

In [ ]:
func(np.array([1,2,3,4,5,6,7]),4)

array([5, 6, 7])

 **Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.**

In [290]:
def extract(arr,dim1,dim2,dim3):
  extract=arr[dim1,dim2,dim3]
  return extract

In [293]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,5]]])
dim1=[0,0,0]
dim2=[0,2,1]
dim3=[1,2,0]
extract(arr,dim1,dim2,dim3)

array([2, 5, 4])

**Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing**

In [ ]:
arr=np.array([1,2,3,4,5,6])

In [ ]:
arr1=arr[arr>2]

array([3, 4, 5, 6])

In [ ]:
arr2=arr[arr<5]

In [ ]:
arr1 & arr2

array([[1, 2, 1, 4]])

 **Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.**

In [295]:
def ext(arr,dim1,dim2):
  return arr[dim1,dim2]
ext(np.array([[1,2],[3,4]]),[1,0],[0,1])

array([3, 2])

**Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.**

In [ ]:
arr=np.eye(3)

In [ ]:
arr+5

array([[6., 5., 5.],
       [5., 6., 5.],
       [5., 5., 6.]])

**Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting**

In [271]:
arr1=np.random.randint(1,5,(1,3))
arr2=np.random.randint(1,5,(3,4))
arr1.reshape(1,1,3)+arr2.reshape(3,4,1)

array([[[4, 4, 5],
        [3, 3, 4],
        [4, 4, 5],
        [3, 3, 4]],

       [[3, 3, 4],
        [3, 3, 4],
        [3, 3, 4],
        [3, 3, 4]],

       [[5, 5, 6],
        [3, 3, 4],
        [3, 3, 4],
        [5, 5, 6]]])

 **Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.**

In [262]:
arr1=np.random.randint(1,5,(1,4))
arr2=np.random.randint(1,5,(4,3))
print(arr1)
print(arr2)
arr2+arr1.reshape((1,4,1))

[[3 1 2 1]]
[[3 4 4]
 [2 4 1]
 [3 3 4]
 [1 2 1]]


array([[[6, 7, 7],
        [3, 5, 2],
        [5, 5, 6],
        [2, 3, 2]]])

**Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.**

In [ ]:
arr1=np.random.randint(1,10,(3,1))
arr2=np.random.randint(1,10,(1,3))
arr1+arr2

array([[11, 15,  8],
       [ 7, 11,  4],
       [13, 17, 10]])

**Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.**

In [270]:
arr1=np.random.randint(1,5,(2,3))
arr2=np.random.randint(1,5,(2,2))
arr1.reshape(1,2,3)*arr2.reshape(2,2,1)

array([[[ 4,  8, 16],
        [ 3,  3,  1]],

       [[ 1,  2,  4],
        [ 9,  9,  3]]])

**Calculate column wise mean for the given array:**

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
np.mean(arr,axis=0)

array([2.5, 3.5, 4.5])

 **Find maximum value in each row of the given array:**/


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr,axis=1)

array([3, 6])

**For the given array, find indices of maximum value in each column.**

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
np.where(arr==np.max(arr,axis=0))

(array([1, 1, 1]), array([0, 1, 2]))

 **For the given array, apply custom function to calculate moving sum along rows.**

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
def sum(a,b):
  return a+b

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15])

**In the given array, check if all elements in each column are even.**

In [ ]:
arr = np.array([[2, 4, 6], [3, 5, 7]])

In [ ]:
np.all(arr%2==0,axis=0)

array([False, False, False])

 **Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix**.

In [ ]:
original_array = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
original_array.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

**Create a function that takes a matrix as input and returns the flattened array.**

In [ ]:
def flat_array(arr):
  return arr.flatten()

In [ ]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
flat_array(input_matrix)

array([1, 2, 3, 4, 5, 6])

**Write a function that concatenates two given arrays along a specified axis**

In [ ]:
def concat(arr1,arr2):
  return np.concatenate((arr1,arr2),axis=0)

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [ ]:
concat(array1,array2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**Create a function that splits an array into multiple sub-arrays along a specified axis**

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
np.split(original_array,axis=0,indices_or_sections=3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

**Write a function that inserts and then deletes elements from a given array at specified indices**.

In [ ]:
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
for i in range(len(indices_to_insert)):
  a=np.insert(original_array,indices_to_insert[i],values_to_insert[i])
print(a)
for i in indices_to_delete:
  a=np.delete(a,i)
print(a)

[ 1  2  3  4 11  5]
[1 3 4 5]


 **Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`**

In [ ]:
arr1=np.random.rand(10)
arr2=np.random.randint(1,10,(3,10))

In [ ]:
arr1+arr2

array([[1.80729865, 7.11058379, 5.32769088, 5.76046643, 7.17814174,
        2.59226834, 8.07512941, 8.68101829, 5.87121979, 9.62392767],
       [5.80729865, 5.11058379, 2.32769088, 1.76046643, 2.17814174,
        2.59226834, 2.07512941, 6.68101829, 2.87121979, 3.62392767],
       [7.80729865, 8.11058379, 8.32769088, 2.76046643, 9.17814174,
        4.59226834, 9.07512941, 8.68101829, 3.87121979, 3.62392767]])

**Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.**

In [ ]:
arr1=np.arange(10,0,-1)
arr2=np.arange(1,11,1)

In [ ]:
arr2-arr1


array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9])

**Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.**

In [ ]:
arr1=np.random.randint(1,5,(1,1))

In [ ]:
arr2=np.random.randint(1,5,(2,6))

In [ ]:
arr1*arr2

array([[ 9,  6, 12, 12,  3,  6],
       [ 6,  6,  3,  6,  9,  9]])

**Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.**

In [ ]:
arr1=np.arange(2,10+1,2)

In [ ]:
arr2=np.arange(1,5+1)

In [ ]:
arr1/arr2

array([2., 2., 2., 2., 2.])

**Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise**

In [ ]:
arr1=np.arange(1,5+1)

In [ ]:
arr2=np.arange(5,1-1,-1)

In [ ]:
arr1**arr2

array([ 1, 16, 27, 16,  5])

**Write a function that counts the occurrences of a specific substring within a NumPy array of strings.**

In [ ]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])


In [ ]:
arr=np.char.count(arr,'hello')

In [ ]:
np.sum(arr)

3

**Write a function that extracts uppercase characters from a NumPy array of strings.**

In [ ]:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])


In [ ]:
l=[]
for i in arr:
  for j in i:
    if j.isupper():
      l.append(j)
l

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

**Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.**

In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
np.char.replace(arr,"ap","mm")

array(['mmple', 'banana', 'grmme', 'pinemmple'], dtype='<U9')

**Write a function that concatenates strings in a NumPy array element-wise.**

In [ ]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
np.char.add(arr1,arr2)


array(['HelloOpen', 'WorldAI'], dtype='<U9')

**Write a function that finds the length of the longest string in a NumPy array.**

In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
from functools import reduce
reduce(lambda x,y:max(x,y),arr)

'pineapple'

**Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.**

In [ ]:
arr=np.random.randint(1,1000,(100))
print(np.mean(a))
print(np.median(a))
print(np.var(a))
print(np.std(a))

6.375
7.0
4.484375
2.117634293262177


**Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.**


In [ ]:
arr=np.random.randint(1,100,(50,))
print(np.percentile(arr,25))
print(np.percentile(arr,75))

28.0
73.25


**Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.**

In [ ]:
a=np.random.randint(1,10,(2,4))
b=np.random.randint(1,10,(4,4))
np.corrcoef(a,b)

array([[ 1.        , -0.6882472 ,  0.20751434,  0.7806311 , -0.8705715 ,
         0.74926865],
       [-0.6882472 ,  1.        , -0.30151134, -0.10976426,  0.31622777,
        -0.81649658],
       [ 0.20751434, -0.30151134,  1.        ,  0.23166619, -0.38138504,
         0.73854895],
       [ 0.7806311 , -0.10976426,  0.23166619,  1.        , -0.97189419,
         0.44811071],
       [-0.8705715 ,  0.31622777, -0.38138504, -0.97189419,  1.        ,
        -0.64549722],
       [ 0.74926865, -0.81649658,  0.73854895,  0.44811071, -0.64549722,
         1.        ]])

**Create two matrices and perform matrix multiplication using NumPy's `dot` function.**

In [ ]:
a=np.random.randint(1,10,(2,4))
b=np.random.randint(1,10,(4,4))
a@b

array([[ 82,  86,  71, 127],
       [ 73,  87,  65, 120]])

**Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.**

In [ ]:
a=np.random.randint(10,100,(50))
print(np.percentile(a,50))
print(np.percentile(a,10))
print(np.percentile(a,90))
print("-----quartile-----")
print("first quartile",np.percentile(a,25))
print("third quartile",np.percentile(a,75))

52.5
19.300000000000004
85.1
-----quartile-----
first quartile 34.25
third quartile 72.5


**Create a NumPy array of integers and find the index of a specific element.**

In [ ]:
arr=np.array([1,2,3,4,5])
np.where(arr==3)

(array([2]),)

**Generate a random NumPy array and sort it in ascending order.**

In [ ]:
arr=np.random.random(5)
np.sort(arr)

array([0.04926686, 0.31040844, 0.53592559, 0.88708257, 0.89019472])

**Filter elements >20  in the given NumPy array.**




In [ ]:
arr = np.array([12, 25, 6, 42, 8, 30])
list(filter(lambda x:x>20,arr))

[25, 42, 30]

**Filter elements which are divisible by 3 from a given NumPy array.**

In [ ]:
arr = np.array([1, 5, 8, 12, 15])
def filter_cond(a):
  if a%3==0:
    return True
  else:
    return False
list(filter(filter_cond,arr))

[12, 15]

**Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.**

In [ ]:
a=np.arange(20,50)

In [ ]:
def filtercond(a):
  if a>=20 and a<=40:
    return True
  else:
    return False
list(filter(filtercond,a))

[20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40]

**For the given NumPy array, check its byte order using the `dtype` attribute byteorder.**

In [ ]:
arr = np.array([1, 2, 3])
arr.dtype.byteorder

'='

**For the given NumPy array, perform byte swapping in place using `byteswap()`**

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

 **For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.**

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)



In [ ]:
arr.dtype.byteorder

'='

In [ ]:
brr=arr.byteswap().newbyteorder('>')

In [ ]:
brr.dtype

dtype('>i4')

**For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.**



In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.dtype.byteorder

'='

In [ ]:
if arr.dtype.byteorder==">":
  swaparr=arr.byteswap().newbyteorder('<')
else:
  swaparr=arr.byteswap().newbyteorder('>')
swaparr.dtype.byteorder

'>'

 **For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.**

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
import sys
sys.byteorder

'little'

In [ ]:
if arr.dtype.byteorder=="=":
  print("swapping is not necessary")
elif (arr.dtype.byteorder==">" and sys.byteorder=="little") or (arr.dtype.byteorder=="<" or sys.byteorder=="big"):
  print("byte swap is nesscessary")
else:
  print("not nesscessary")

swapping is not necessary


**Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.**

In [ ]:
arr1=np.arange(1,10+1)
copy_arr=arr1#shallow copy
print("before modification",arr1)
print("before modification",copy_arr)
copy_arr[0]=2
print("after modification",arr1)
print("after modification",copy_arr)

#deepcopy
arr1=np.arange(1,10+1)
copy_arr=arr1.copy()#deep copy
print("before modification",arr1)
print("before modification",copy_arr)
copy_arr[0]=2
print("after modification",arr1)
print("after modification",copy_arr)

before modification [ 1  2  3  4  5  6  7  8  9 10]
before modification [ 1  2  3  4  5  6  7  8  9 10]
after modification [ 2  2  3  4  5  6  7  8  9 10]
after modification [ 2  2  3  4  5  6  7  8  9 10]
before modification [ 1  2  3  4  5  6  7  8  9 10]
before modification [ 1  2  3  4  5  6  7  8  9 10]
after modification [ 1  2  3  4  5  6  7  8  9 10]
after modification [ 2  2  3  4  5  6  7  8  9 10]


**Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix**

In [ ]:
arr=np.random.randint(1,5,(3,3))
print(arr)
view_slice=arr[1:2,2]
print(view_slice)
view_slice[0]=1
print(arr)

[[4 4 2]
 [3 1 4]
 [4 3 1]]
[4]
[[4 4 2]
 [3 1 1]
 [4 3 1]]


 **Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the orignal array_a**

In [ ]:
array_a=np.arange(1,12+1).reshape(4,3)
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
veiw_b=array_a[2:,1]

In [ ]:
veiw_b+5

array([13, 16])

In [ ]:
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.**

In [ ]:
orig_array=np.arange(1,9).reshape(2,4)
reshape_view=orig_array.view().reshape(4,2)
print(orig_array,"before any change")
print(reshape_view,"before any change")
reshape_view[0]=1
print(orig_array,"after change")
print(reshape_view,"after change")


[[1 2 3 4]
 [5 6 7 8]] before any change
[[1 2]
 [3 4]
 [5 6]
 [7 8]] before any change
[[1 1 3 4]
 [5 6 7 8]] after change
[[1 1]
 [3 4]
 [5 6]
 [7 8]] after change


**Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.**

In [ ]:
data=np.arange(1,13).reshape(3,4)
print(data)
data_copy=data[data>5]
print(data_copy)
data_copy[0]=1
print(data_copy)
print(data)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 6  7  8  9 10 11 12]
[ 1  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them**

In [ ]:
A=np.arange(1,13).reshape(3,4)
B=np.arange(13,25).reshape(3,4)
print(A+B)
print(A-B)

[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]


**Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.**

In [ ]:
c=np.arange(1,7).reshape(3,2)
d=np.arange(1,9).reshape(2,4)
c@d


array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68]])

**Create a matrix `E` and find its transpose.**

In [ ]:
E=np.random.rand(3,4)
print(E)
print("transpose of it")
print(E.T)

[[0.80340014 0.46886518 0.50536581 0.61545521]
 [0.01334993 0.65251322 0.22762824 0.59629966]
 [0.40071122 0.56183581 0.18654421 0.95730216]]
transpose of it
[[0.80340014 0.01334993 0.40071122]
 [0.46886518 0.65251322 0.56183581]
 [0.50536581 0.22762824 0.18654421]
 [0.61545521 0.59629966 0.95730216]]


**Generate a square matrix `F` and compute its determinant.**

In [ ]:
F=np.eye(6)

In [ ]:
np.linalg.det(F)

1.0

**Create a square matrix `G` and find its inverse.**

In [ ]:
G=np.eye(3)

In [ ]:
G=G+3

In [ ]:
np.linalg.inv(G)

array([[ 0.7, -0.3, -0.3],
       [-0.3,  0.7, -0.3],
       [-0.3, -0.3,  0.7]])